// import { cards } from "../Pages/coursPage/CardsInfo";



export const UserInformation=[
    {id : 1,
     name : "mmdAbd",
     studentNumber : 40012102048 ,
     type : "Teacher",
     profileImg : "",
     email : "mmd@gmail.com" ,
     password : 12345678,
     study: "دکترای مخابرات",
     university: "صنعتی خاتم الانبیا بهبهان",
     aboutMe : "",
     aboutTeacher : "",
     corsesId : [],
     myRequests:[],
    },
//     {
//      id: 2,
//      name: "حسین شریف",
//      studentNumber : 40012102049 ,
//      type : "User",
//      profileImg : "",
//      email : "mmd@gmail.com" ,
//      password : 12345678,
//      study: "دکترای مخابرات",
//      university: "صنعتی خاتم الانبیا بهبهان",
//      aboutMe : "",
//      aboutTeacher : "",
//      corsesId : [],
//     },
//     {
//      id: 3,
//      name: "اکبر کاظمی",
//      studentNumber : 40012102050 ,
//      type : "User",
//      profileImg : "",
//      email : "mmd@gmail.com" ,
//      password : 12345678,
//      study: "لیسانس کامپیوتر",
//      university: "صنعتی خاتم الانبیا بهبهان",
//      aboutMe : "",
//      aboutTeacher : "",
//      corsesId : [],
//     },
//     {
//      id: 4,
//      name: "علی حسینی",
//      studentNumber : 40012102051 ,
//      type : "User",
//      profileImg : "",
//      email : "mmd@gmail.com" ,
//      password : 12345678,
//      study: "ارشد برق",
//      university: "شیراز",
//      aboutMe : "",
//      aboutTeacher : "",
//      corsesId : [],
//     },
//     {
//      id: 5,
//      name: "یوسف قنبری",
//      studentNumber : 40012102052 ,
//      type : "User",
//      profileImg : "",
//      email : "mmd@gmail.com" ,
//      password : 12345678,
//      study: "لیسانس معماری",
//      university: "شهید بهشتی",
//      aboutMe : "",
//      aboutTeacher : "",
//      corsesId : [],
//     },
//     {
//      id: 6,
//      name: "فیروز اکرمی",
//      studentNumber : 40012102053 ,
//      type : "User",
//      profileImg : "",
//      email : "mmd@gmail.com" ,
//      password : 12345678,
//      study: "لیسانس کامپیوتر",
//      university: "صنعتی اصفهان",
//      aboutMe : "",
//      aboutTeacher : "",
//      corsesId : [],
//     },
    {
     id: 7,
     name: "محمد کریمی",
     studentNumber : "Admin" ,
     type : "Admin",
     profileImg : "",
     email : "mmd@gmail.com" ,
     password : "Admin",
    //  study: "لیسانس جانور شناسی",
    //  university: "صنعتی شریف",
    //  aboutMe : "",
    //  aboutTeacher : "",
    //  corsesId : [],
    //  myRequests:[],
    },
    {
     id: 8,
     name: "علی رضایی",
     studentNumber : 40012102055 ,
     type : "Teacher",
     profileImg : "",
     email : "mmmd@gmail.com" ,
     password : 12345678,
     study: "کامپیوتر",
     university: "",
     aboutMe : "!سلام من",
     aboutTeacher : "",
     corsesId : [],
     myRequests:[
        { RequestsId: 1, title: "آموزش React", status: "pending" },
        { RequestsId: 2, title: "دوره طراحی وب", status: "approved" },
        { RequestsId: 3, title: "آموزش فیگما", status: "rejected" },
    ],
    },
    {
     id: 9,
     name: "نگار محمدی",
     studentNumber : 40012102056 ,
     type : "Teacher",
     profileImg : "",
     email : "mmd@gmail.com" ,
     password : 12345678,
     study: "کامپیوتر",
     university: "تهران",
     aboutMe : "",
     aboutTeacher : "",
     corsesId : [],
     myRequests:[],
    },
//     {
//         id: 100,
//         name: "نگار",
//         studentNumber : 40012102070 ,
//         type : "User",
//         profileImg : "",
//         email : "mbbbmd@gmail.com" ,
//         password : 12345678,
//         study: "کامپیوتر",
//         university: "تهران",
//         aboutMe : "",
//         aboutTeacher : "",
//         corsesId : [],
//     }

]

